@baseUrl=http://localhost:8082/v1

# user registration
POST {{baseUrl}}/user/register
Content-Type: application/json

{
  "verify_key": "services.lytranvinh@gmail.com",
  "verify_purpose": "TEST_USER",
  "verify_type": 1
}