
networks:
  go-ecommerce-network:
    driver: bridge

services:

  # Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: go-ecommerce-prometheus
    restart: unless-stopped
    volumes:
      - ../prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ../data/prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - "9090:9090"
    networks:
      - go-ecommerce-network

  # Grafana
  grafana:
    image: grafana/grafana
    container_name: go-ecommerce-grafana
    hostname: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SING_UP=false
      - GF_SERVER_DOMAIN=localhost
      #enable logger
      - GF_LOG_MODE=console file
      - GF_LOG_FILTERS=alerting.notifier.slack:debug alermanager:debug ngalert:debug

    volumes:
      - ../grafana-storage:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - go-ecommerce-network

  # Exporters for Prometheus
  node-exporter:
    image: prom/node-exporter:latest
    container_name: go-ecommerce-node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - --path.procfs=/host/proc
      - --path.rootfs=/rootfs
      - --path.sysfs=/host/sys
      - --collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)
    ports:
      - "9100:9100"
    networks:
      - go-ecommerce-network

  # mysqld-exporter
  mysqld-exporter:
    image: prom/mysqld-exporter
    container_name: go-ecommerce-mysqld-exporter
    ports:
      - "9104:9104"
    command:
      - '--collect.engine_innodb_status'
      - '--collect.info_schema.processlist'
      - '--collect.info_schema.tables'
      - '--collect.info_schema.query_response_time'
      - '--collect.perf_schema.file_events'
      - '--collect.perf_schema.eventsstatements'
      - '--collect.perf_schema.indexiowaits'
      - '--collect.global_status'
      #      - '--ignore-tables'
      - '--config.my-cnf=/etc/mysql/.my.cnf'
    volumes:
      - ../mysqld-exporter/.my.cnf:/etc/mysql/.my.cnf
    environment:
      - DATA_SOURCE_NAME=root:root1234@tcp(mysql:3316)/
#    depends_on:
#      - mysql
    networks:
      - go-ecommerce-network

  # Redis Exporter
  redis-exporter:
    image: oliver006/redis_exporter
    command: -redis.addr redis://redis-master:6379
    ports:
      - 9121:9121
    networks:
      - go-ecommerce-network

  #  logstash-exporter:
  #    image: alxrem/prometheus-logstash-exporter
  #    container_name: go-ecommerce-logstash-exporter
  #    command: ["-logstash.host", "logstash"]
  #    platform: linux/arm64/v8
  #    environment:
  #      LOGSTASH_URI: "http://logstash:9600" # Kết nối tới Logstash API
  #    ports:
  #      - "9304:9304" # Cổng Logstash Exporter cho Prometheus
  #    networks:
  #      - go-ecommerce-network
  #    depends_on:
  #      - logstash
