server:
  port: 8082
databases:
  - user: admin
    password: admin
    host: localhost
    dbName: go-ecommerce
  - user: order
    password: order
    host: localhost
    dbName: go-ecommerce-order
sercurity:
  jwt:
    key: abc123
redis:
  host: localhost
  port: 6379
elasticsearch:
  host: localhost
  port: 9200
rabbitmq:
  host: localhost
  port: 5672
  user: guest
  password: guest
kafka:
  host: localhost
  port: 9092

