server:
    port: 8082
    mode: 'dev' # default: dev, options: dev, prod

mysql:
    host: 127.0.0.1
    port: 3316
    username: root
    password: root1234
    dbname: ecommerce
    maxIdleConns: 10
    maxOpenConns: 100
    connMaxLifetime: 3600

mongodb:
    host: 127.0.0.1
    port: 27017
    username: root
    password: root123
    dbname: go_ecommerce
    maxIdleConns: 10
    maxOpenConns: 100
    connMaxLifetime: 3600

logger:
    level: debug
    file_log_name: './storages/log/dev.001.log'
    max_size: 500
    max_backups: 3
    max_age: 30
    compress: true

redis:
    host: 127.0.0.1
    port: 6379
    password:
    db: 0
    pool_size: 10
    master_name: mymaster
    sentinel_addrs:
        - 127.0.0.1:26379
        - 127.0.0.1:26380
        - 127.0.0.1:26381

kafka_send_otp:
    host: localhost
    port: 9094
    topic: send_otp

smtp:
    host: smtp.gmail.com
    port: 587
    username:
    password:

send_grid:
    api_key: '${send_grid_api_key}'

rabbitmq:
    url_rb_d: ''

kafka:
    tcp_host: '127.0.0.1:9094'
    topic_service_send_mail: 'go-service-send-mail-otp'

jwt:
    token_hour_lifespan: 1
    jwt_expiration: 1h
    api_secret: 'xxx.yyy.zzz'

monitoring:
    prometheus_port: 9090
    grafana_port: 3000
    grafana_admin_user: admin
    grafana_admin_password: admin
    node_exporter_port: 9100
    redis_exporter_port: 9121
    mysql_exporter_port: 9104
    kafka_exporter_port: 9308

logstash:
    host: 127.0.0.1
    port: 5044
