global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "go-ecommerce-prometheus"
    scrape_interval: 5s
    static_configs:
      - targets:
          - "localhost:9090" # Prometheus itself
  
  - job_name: "go-ecommerce-node-exporter"
    scrape_interval: 5s
    static_configs:
      - targets:
          - "node-exporter:9100" # Node Exporter

  - job_name: 'go-ecommerce'
    scrape_interval: 5s
    static_configs:
      - targets: 
        - 'host.docker.internal:8082'
      
  